export const site = {
  name: "Nostr Dev Kit",
  shortName: "NDK",
  title: "Nostr Dev Kit",
  description:
    "The Nostr Dev Kit project (aka rust-nostr) is building tools and libraries designed to be a solid foundation for nostr software.",
  url: "https://nostrdevkit.org",
  logo: "/assets/logo.svg",
  docsUrl: "https://doc.rust-nostr.org/",
  githubUrl: "https://github.com/nostrdevkit",
  repositoryUrl: "https://github.com/nostrdevkit",
  themeColor: "#0b0714",
  keywords: [
    "Nostr",
    "Nostr SDK",
    "Nostr development kit",
    "rust-nostr",
    "Rust",
    "Python",
    "Kotlin",
    "Swift",
    "WebAssembly",
    "open source software",
  ],
};
